version: '3.7'

networks:
    tiktok:
        driver: bridge

services:

    mysql:
        container_name: mysql
        image: mysql:latest
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=tiktok
            - MYSQL_USER=tiktok
            - MYSQL_PASSWORD=tiktok
            - TZ=Asia/Shanghai
        volumes:
            - ./config/sql:/docker-entrypoint-initdb.d/
            - ./data/mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - tiktok

    redis:
        container_name: redis
        image: "redis:latest"
        restart: always
        ports:
            - 6379:6379
        volumes:
            - ./data/redis:/data
        environment:
            - REDIS_PASSWORD=tiktok
            - ALLOW_EMPTY_PASSWORD=no
        networks:
                - tiktok

    zookeeper:
        container_name: zookeeper
        image: "confluentinc/cp-zookeeper:7.5.0"
        restart: always
        ports:
            - 2181:2181
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        volumes:
            - ./data/zookeeper/data:/var/lib/zookeeper/data
            - ./data/zookeeper/log:/var/lib/zookeeper/log
        networks:
            - tiktok

    kafka:
        container_name: kafka
        image: "confluentinc/cp-kafka:7.5.0"
        restart: always
        depends_on:
            - zookeeper
        ports:
            - 9092:9092
            - 29092:29092
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:29092
            KAFKA_LISTENERS: PLAINTEXT://:9092,EXTERNAL://:29092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
            KAFKA_HEAP_OPTS: "-Xmx1G -Xms256M"
            ALLOW_PLAINTEXT_LISTENER: "yes"
        volumes:
            - ./data/kafka/data:/var/lib/kafka/data
        networks:
            - tiktok

    etcd:
        container_name: etcd
        image: "quay.io/coreos/etcd:v3.5.5"
        restart: always
        ports:
            - 2379:2379
            - 2380:2380
        environment:
            - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
            - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
            - ETCD_API=3
            - ALLOW_NONE_AUTHENTICATION=yes
        volumes:
            - ./docker:/script
            - ./config:/config
            - ./data/etcd:/etcd-data
        networks:
            - tiktok
        entrypoint: ["sh", "-c", "chmod +x /script/etcd-monitor.sh && /script/etcd-monitor.sh & exec etcd"]

    etcd-keeper:
        hostname: etcdkeeper
        image: evildecay/etcdkeeper
        environment:
            - ETCD_HOSTS=http://etcd:2379
            - SW_STORAGE_ETCD_CLUSTER_NODES=etcd:2379
            - HOST=0.0.0.0
            - HOSTNAME=etcd-keeper
        links:
            - etcd
        ports:
            - 8099:8080
        depends_on:
            - etcd
        networks:
            - tiktok
